### ISSUE TITLE
Connection Bug

### ISSUE THREAD

**Issue by l-404-l** [jchristn/DatabaseWrapper#11]
'The given key '28265' was not present in the dictionary.' when trying to connect to my server I run on MariaDB | DatabaseWarpper V 4.0.0.1

**Comment by l-404-l** [comment]
`var client = new DatabaseClient(DbTypes.Mysql, "0.0.0.0", 3306, "", "", "");`

`System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Message=The given key '28265' was not present in the dictionary.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MySql.Data.MySqlClient.MySqlField.SetFieldEncoding()
   at MySql.Data.MySqlClient.MySqlField.set_CharacterSetIndex(Int32 value)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnData(MySqlField field)
   at MySql.Data.MySqlClient.NativeDriver.GetColumnsData(MySqlField[] columns)
   at MySql.Data.MySqlClient.Driver.GetColumns(Int32 count)
   at MySql.Data.MySqlClient.ResultSet.LoadColumns(Int32 numCols)
   at MySql.Data.MySqlClient.ResultSet..ctor(Driver d, Int32 statementId, Int32 numCols)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlDataReader.Close()
   at MySql.Data.MySqlClient.MySqlCommand.ResetReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at DatabaseWrapper.Mysql.DatabaseClient.Query(String query)
   at DatabaseWrapper.Mysql.DatabaseClient.SetMaxStatementLength()
   at DatabaseWrapper.Mysql.DatabaseClient..ctor(DatabaseSettings settings)
   at DatabaseWrapper.DatabaseClient..ctor(DbTypes dbType, String serverIp, Int32 serverPort, String username, String password, String instance, String database)
   at Project.Program.Main(String[] args) in D:\gitHubReleases\LogicServer\Program.cs:line 11

  This exception was originally thrown at this call stack:
    [External Code]
    Project.Program.Main(string[]) in Program.cs`

Is all I try and it gives me that error

**Comment by jchristn** [comment]
Got it, thank you.  I'll have to move the debug settings into the ```Settings``` object so I can get more clarity on the query that is throwing this.  I have MariaDB installed locally and will get to this shortly.

**Comment by jchristn** [comment]
Hi @[l-404-l](https://github.com/l-404-l) could you help reproduce this?  I installed MariaDB along with HeidiSQL and it seems to work fine for me.

I also notice that you have no credentials supplied in your constructor.  Could you add them?

Here's what I have currently:

MariaDB: 10.6.8-MariaDB
HeidiSQL: 11.3.0.6295

My table:
![image](https://user-images.githubusercontent.com/1421081/170760225-b6ae6847-879f-423d-9006-a825268c022a.png)

The INSERT:
```
USE `test`;
INSERT INTO `person` (firstname, lastname, birthdate, `localtime`, age, notes, persontype, ishandsome) VALUES
('joel', 'christner', '2000-01-01', '2022-05-27', 45, 'hello', 'human', 1);
```

The SELECT:
![image](https://user-images.githubusercontent.com/1421081/170760319-48fefbae-87bf-46c0-af25-4d65a294e96e.png)

I added a new project called ```Test.DatabaseConsole``` (and made a minor enhancement to move logging into settings) in v4.1.2, which I'm committing now.  The output from there is:
```
C:\Code\Misc\DatabaseWrapper-4.0\Test.DatabaseConsole\bin\Debug\net6.0>test.databaseconsole
DB type [sqlserver|mysql|postgresql|sqlite]: [mysql] mysql
Ensure the database has been created beforehand.

User: [root]
Pass: [redacted]
Host: [localhost]
Port: [3306] 3307
Database: [test]
Command [? for help]: ?

Available commands:
  q         quit
  ?         help, this menu
  cls       clear the screen
  debug     enable/disable debug, currently True
  [query]   execute a query

Command [? for help]: select * from person;

(none)

Command [? for help]: select * from person;

[
  {
    "id": 1,
    "firstname": "joel",
    "lastname": "christner",
    "birthdate": "2000-01-01T00:00:00Z",
    "nullablebirthdate": null,
    "localtime": "2022-05-27T00:00:00Z",
    "nullablelocaltime": null,
    "age": 45,
    "nullableage": null,
    "notes": "hello",
    "persontype": "human",
    "nullablepersontype": null,
    "ishandsome": 1,
    "picture": null
  }
]

1 row(s)

Command [? for help]:
```
Note that I set up MariaDB to run on 3307 instead of 3306, since I'm also using MySQL.

Commit: https://github.com/jchristn/DatabaseWrapper/commit/85c62743b5731ec413d110af39cdf75de447edcc
NuGet: https://www.nuget.org/packages/DatabaseWrapper/4.1.2

**Comment by l-404-l** [comment]
the way i fixed it is manually updating Mysql.Data and everything worked perfectly fine

**Comment by jchristn** [comment]
Got it.  The latest version (4.1.2) should have the latest Mysql.Data in it too.  Thanks for letting me know!
