### ISSUE TITLE
MySql Insert into table with no primary key results in MySqlException

### ISSUE THREAD

**Issue by paulnorstrom** [jchristn/DatabaseWrapper#7]
--- Bug Report ---
Operating system and version: Windows 10 
Framework and runtime: .NET Core 3.1
Issue encountered: MySql syntax error when inserting into table with no primary key. The insert seems to work fine, the error occurs in the post-retreiveal section when the retrievalQuery is created since primaryKeyColumn is null.

Expected behavior: No Exception? Perhaps a IsNullOrEmpty check on primaryKeyColumn and return of the original results instead.
Steps to reproduce: I have a mysql test database and a ms sql test database with sample data. The TestDB in SqlServer has one table called Inventory. The table description can be seen in the output log.

Sample code encapsulating the problem:

                // Program idea: Copy db tables and content from ms sql to mysql.

                var tables = mssql_client.ListTables();
                foreach (var table in tables)
                {
        
                    var cols = mssql_client.DescribeTable(table);
                    var primkey = mssql_client.GetPrimaryKeyColumn(table);
                    Console.WriteLine($"TableName: {table}, PrimaryKey: {primkey}");
                    
                    if (mysql_client.TableExists(table))
                    {
                        mysql_client.DropTable(table);
                    }

                    mysql_client.CreateTable(table, cols);

                    var data = mssql_client.Select(table, null, null, null, new Expression());

                    if (data != null && data.Rows.Count > 0)
                    {

                        var dictlist = data.AsEnumerable().Select(
                                row => data.Columns.Cast<DataColumn>().ToDictionary(
                                column => column.ColumnName,
                                column => row[column]
                )).ToList();
                        foreach (var item in dictlist)
                        {
                            var res = mysql_client.Insert(table, item);
                        }
                    }

                }

Exception details: [insert exception output here] Stack trace: [if appropriate]

[DatabaseWrapper.SqlServer] query: SELECT TABLE_NAME FROM TestDB.INFORMATION_SCHEMA.Tables WHERE TABLE_TYPE = 'BASE TABLE'
[DatabaseWrapper.SqlServer] result: 1 rows
[DatabaseWrapper.SqlServer] query: SELECT   col.TABLE_NAME, col.COLUMN_NAME, col.IS_NULLABLE, col.DATA_TYPE, col.CHARACTER_MAXIMUM_LENGTH, con.CONSTRAINT_NAME FROM INFORMATION_SCHEMA.COLUMNS col LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE con ON con.COLUMN_NAME = col.COLUMN_NAME AND con.TABLE_NAME = col.TABLE_NAME WHERE col.TABLE_NAME='Inventory' AND col.TABLE_CATALOG='TestDB'
[DatabaseWrapper.SqlServer] result: 3 rows
[DatabaseWrapper.SqlServer] query: SELECT   col.TABLE_NAME, col.COLUMN_NAME, col.IS_NULLABLE, col.DATA_TYPE, col.CHARACTER_MAXIMUM_LENGTH, con.CONSTRAINT_NAME FROM INFORMATION_SCHEMA.COLUMNS col LEFT JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE con ON con.COLUMN_NAME = col.COLUMN_NAME AND con.TABLE_NAME = col.TABLE_NAME WHERE col.TABLE_NAME='Inventory' AND col.TABLE_CATALOG='TestDB'
[DatabaseWrapper.SqlServer] result: 3 rows
TableName: Inventory, PrimaryKey:
[DatabaseWrapper.Mysql] query: SHOW TABLES
[DatabaseWrapper.Mysql] result: 9 rows
[DatabaseWrapper.Mysql] query: DROP TABLE IF EXISTS `Inventory`
[DatabaseWrapper.Mysql] result: 0 rows
[DatabaseWrapper.Mysql] query: CREATE TABLE `Inventory` (`id` int NULL , `name` varchar(50) NULL , `quantity` int NULL ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4
[DatabaseWrapper.Mysql] result: 0 rows
[DatabaseWrapper.SqlServer] query: SELECT *  FROM [Inventory]
[DatabaseWrapper.SqlServer] result: 2 rows
[DatabaseWrapper.Mysql] query: START TRANSACTION; INSERT INTO `Inventory` (`id`,`name`,`quantity`) VALUES (1,'banana',150); SELECT LAST_INSERT_ID() AS id; COMMIT;
[DatabaseWrapper.Mysql] result: 1 rows
[DatabaseWrapper.Mysql] query: SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Inventory' AND TABLE_SCHEMA='classicmodels'
[DatabaseWrapper.Mysql] result: 3 rows
[DatabaseWrapper.Mysql] query: SELECT * FROM `Inventory` WHERE =0
---
An exception was encountered which triggered this message.
  Method: Main
  Text: Outer exception
  Type: MySql.Data.MySqlClient.MySqlException
  Data: System.Collections.ListDictionaryInternal
  Inner:
  Message: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=0' at line 1
  Source: MySql.Data
  StackTrace:    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at DatabaseWrapper.Mysql.DatabaseClient.Query(String query)
   at DatabaseWrapper.Mysql.DatabaseClient.Insert(String tableName, Dictionary`2 keyValuePairs)
   at DatabaseWrapper.DatabaseClient.Insert(String tableName, Dictionary`2 keyValuePairs)
   at Test.Sqlite.Program.Main(String[] args) in C:\git\testrepos\DBTest\DBTestWrapper\Program.cs:line 72
  Stack: StackToString <= ExceptionConsole <= Main
  Line: 0
  File:
  ToString: MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=0' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at DatabaseWrapper.Mysql.DatabaseClient.Query(String query)
   at DatabaseWrapper.Mysql.DatabaseClient.Insert(String tableName, Dictionary`2 keyValuePairs)
   at DatabaseWrapper.DatabaseClient.Insert(String tableName, Dictionary`2 keyValuePairs)
   at Test.Sqlite.Program.Main(String[] args) in C:\git\testrepos\DBTest\DBTestWrapper\Program.cs:line 72
---
--- End ---

**Comment by jchristn** [comment]
Hi @paulnorstrom this is expected behavior.  In order to return the inserted row consistently across different DBMS, MySQL (being one of the only ones that won't return the row directly) requires that the created row be selected after.  Thus, one constraint within the library is that each table must have a primary key.

You are welcome to clone and modify the source as you see fit.  The modification to make this work is minimal; it's not something I'm willing to do in the library because of the aforementioned constraint (I use it within my own packages and within my own ORM, and they depend on this capability), however, I'm happy to help you get it working the way you want.  Drop me an email if you like.  Cheers, Joel

**Comment by paulnorstrom** [comment]
Hi Joel,
thank you for your reply and thank you very much for sharing this great library!

I understand.
Not sure what i'll do.
I like the simplicity of depending of nuget packages and we dont have our own nuget server yet.

But yes it was an easy "fix", I already cloned your repo and tested it.

/Paul

Hämta Outlook för Android<https://aka.ms/AAb9ysg>

________________________________
